steps:
  # Tests
  - name: python
    id: 'Test'
    entrypoint: 'bash'
    args:
      - -c
      - |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m pytest -vv
  # Deploy the cloud function
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-function
    env:
      - 'SUPABASE_URL=${_SUPABASE_URL}'
      - 'SERVICE_ROLE_KEY=${_SERVICE_ROLE_KEY}'
    args:
      - functions
      - deploy
      - invite-user-function
      - --gen2
      - --runtime=python310
      - --region=europe-west2
      - --source=.
      - --entry-point=main
      - --trigger-http
      - --memory=256MiB
      - --service-account=${_SERVICE_ACCOUNT}
      - --no-allow-unauthenticated
      - --set-env-vars=SUPABASE_URL=${_SUPABASE_URL}
      - --set-env-vars=SERVICE_ROLE_KEY=${_SERVICE_ROLE_KEY}
      - --set-env-vars=SERVICE_ACCOUNT=${_SERVICE_ACCOUNT}
